/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.glfw2.functions;

private
{
    import core.stdc.config;
    import derelict.glfw2.types;
}


extern(C)
{
    alias nothrow int function()da_glfwInit;
    alias nothrow void function()da_glfwTerminate;
    alias nothrow void function(int*, int*, int*)da_glfwGetVersion;

    alias nothrow void function(GLFWvidmode *, int)da_glfwGetVideoModes;
    alias nothrow void function(GLFWvidmode *)da_glfwGetDesktopMode;

    alias nothrow int function(int, int, int, int, int, int, int, int, int)da_glfwOpenWindow;
    alias nothrow void function(int, int)da_glfwOpenWindowHint;
    alias nothrow void function()da_glfwCloseWindow;
    alias nothrow void function(immutable const(char)*)da_glfwSetWindowTitle;
    alias nothrow void function(int*, int*)da_glfwGetWindowSize;
    alias nothrow void function(int, int)da_glfwSetWindowSize;
    alias nothrow void function(int, int)da_glfwSetWindowPos;
    alias nothrow void function()da_glfwIconifyWindow;
    alias nothrow void function()da_glfwRestoreWindow;
    alias nothrow int function(int)da_glfwGetWindowParam;
    alias nothrow void function(GLFWwindowsizefun)da_glfwSetWindowSizeCallback;
    alias nothrow void function(GLFWwindowclosefun)da_glfwSetWindowCloseCallback;
    alias nothrow void function(GLFWwindowrefreshfun)da_glfwSetWindowRefreshCallback;

    alias nothrow void function()da_glfwPollEvents;
    alias nothrow void function()da_glfwWaitEvents;

    alias nothrow int function(int)da_glfwGetKey;
    alias nothrow int function(int)da_glfwGetMouseButton;
    alias nothrow void function(int*, int*)da_glfwGetMousePos;
    alias nothrow void function(int, int)da_glfwSetMousePos;
    alias nothrow int function()da_glfwGetMouseWheel;
    alias nothrow void function(int)da_glfwSetMouseWheel;
    alias nothrow void function(GLFWkeyfun)da_glfwSetKeyCallback;
    alias nothrow void function(GLFWcharfun)da_glfwSetCharCallback;
    alias nothrow void function(GLFWmousebuttonfun)da_glfwSetMouseButtonCallback;
    alias nothrow void function(GLFWmouseposfun)da_glfwSetMousePosCallback;
    alias nothrow void function(GLFWmousewheelfun)da_glfwSetMouseWheelCallback;

    alias nothrow int function(int, int)da_glfwGetJoystickParam;
    alias nothrow int function(int, float*, int)da_glfwGetJoystickPos;
    alias nothrow int function(int, ubyte*, int)da_glfwGetJoystickButtons;

	
    alias nothrow double function()da_glfwGetTime;
    alias nothrow void function(double)da_glfwSetTime;

    alias nothrow void function()da_glfwSwapBuffers;
    alias nothrow void function(int)da_glfwSwapInterval;
    alias nothrow int function(in char*)da_glfwExtensionSupported;
    alias nothrow void* function(in char*)da_glfwGetProcAddress;
    alias nothrow void function(int*, int*, int*)da_glfwGetGLVersion;
    alias nothrow void function(int)da_glfwEnable;
    alias nothrow void function(int)da_glfwDisable;
}

__gshared
{
    da_glfwInit glfwInit;
    da_glfwTerminate glfwTerminate;
    da_glfwGetVersion glfwGetVersion;
    da_glfwGetVideoModes glfwGetVideoModes;
    da_glfwGetDesktopMode glfwGetDesktopMode;
    da_glfwOpenWindow glfwOpenWindow;
    da_glfwOpenWindowHint glfwOpenWindowHint;
    da_glfwCloseWindow glfwCloseWindow;
    da_glfwSetWindowTitle glfwSetWindowTitle;
    da_glfwGetWindowSize glfwGetWindowSize;
    da_glfwSetWindowSize glfwSetWindowSize;
    da_glfwSetWindowPos glfwSetWindowPos;
    da_glfwIconifyWindow glfwIconifyWindow;
    da_glfwRestoreWindow glfwRestoreWindow;
    da_glfwGetWindowParam glfwGetWindowParam;
    da_glfwSetWindowSizeCallback glfwSetWindowSizeCallback;
    da_glfwSetWindowCloseCallback glfwSetWindowCloseCallback;
    da_glfwSetWindowRefreshCallback glfwSetWindowRefreshCallback;
    da_glfwPollEvents glfwPollEvents;
    da_glfwWaitEvents glfwWaitEvents;
    da_glfwGetKey glfwGetKey;
    da_glfwGetMouseButton glfwGetMouseButton;
    da_glfwGetMousePos glfwGetMousePos;
    da_glfwSetMousePos glfwSetMousePos;
    da_glfwGetMouseWheel glfwGetMouseWheel;
    da_glfwSetMouseWheel glfwSetMouseWheel;
    da_glfwSetKeyCallback glfwSetKeyCallback;
    da_glfwSetCharCallback glfwSetCharCallback;
    da_glfwSetMouseButtonCallback glfwSetMouseButtonCallback;
    da_glfwSetMousePosCallback glfwSetMousePosCallback;
    da_glfwSetMouseWheelCallback glfwSetMouseWheelCallback;
    da_glfwGetJoystickParam glfwGetJoystickParam;
    da_glfwGetJoystickPos glfwGetJoystickPos;
    da_glfwGetJoystickButtons glfwGetJoystickButtons;
    da_glfwGetTime glfwGetTime;
    da_glfwSetTime glfwSetTime;
    da_glfwSwapBuffers glfwSwapBuffers;
    da_glfwSwapInterval glfwSwapInterval;
    da_glfwExtensionSupported glfwExtensionSupported;
    da_glfwGetProcAddress glfwGetProcAddress;
    da_glfwGetGLVersion glfwGetGLVersion;
    da_glfwEnable glfwEnable;
    da_glfwDisable glfwDisable;
}
